OUPUTDIR=dist

default: build

build: clean
	npm install
	export NODE_ENV=production && export PUBLIC_PATH=//cdn.libook.fun:8080/libook-admin-static/ && npm run build
	cp -r ./$(OUPUTDIR)/* ../libook-backend/docker/nginx/www/cdn.libook.fun/public/libook-admin-static
	
clean:
	rm -rf .dll
	rm -rf $(OUPUTDIR)